#! /bin/bash

export MSYS_NO_PATHCONV=1

echo "Running dockerized terraform..."
docker run -it --rm \
	-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
	-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	-e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
        -v $(pwd):/root/terraform \
	-w /root/terraform \
	hashicorp/terraform $@
