name: Destroy Resources

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
  terraform_destroy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT }}
      TF_VAR_aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_region: ${{ secrets.AWS_DEFAULT_REGION }}  
      TF_VAR_aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        run: terraform init -input=false
        working-directory: ./src/main/terraform

      - name: Terraform destroy
        run: terraform destroy
        working-directory: ./src/main/terraform
