name: Scala CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test docker

  terraform_apply:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        run: terraform init -input=false
        working-directory: ./src/main/terraform

      - name: Terraform validation
        run: terraform validate
        working-directory: ./src/main/terraform

      - name: Terraform plan
        run: terraform plan -input=false
        working-directory: ./src/main/terraform  
